name: Deploy to netwatch.freedev.app

on:
  push:
    branches: ["stable"]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  deploy:
    name: Deploy on netwatch.freedev.app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          retries: 3
          retryDelay: 10
